version: "3.2"
services:
  db:
    image: postgres
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data-db:/var/lib/postgresql/data
      - ./ca/server.crt:/var/lib/postgresql/server.crt
      - ./ca/server.key:/var/lib/postgresql/server.key
    ports:
      - 5432:5432
    env_file:
      - data.env
  backend:
    build: ./backend
    env_file:
      - data.env
    volumes:
      - ./backend:/app/backend
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    depends_on:
      - db
  frontend:
    build: ./client
    volumes:
      - ./client:/app
      #One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
  crawler:
    build: ./housecrawler
    env_file:
      - data.env
    depends_on:
      - db
