on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        run: cd backend && docker build -t mycontainerhub.azurecr.io/daftiecrawler_backend:latest .
