on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          login-server: mycontainerhub.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Building and Pushing backend container
        run: |
          cd backend
          docker build . -t mycontainerhub.azurecr.io/daftiecrawler_backend:latest
          docker push mycontainerhub.azurecr.io/daftiecrawler_backend:latest
